name: sync theme submodules

on:
  push:
    branches: main

  schedule:
     - cron: "00 14 * * *"

  workflow_dispatch:


jobs:
  sync_theme_submodules:
    if: github.repository_owner == 'ioos' # only run if ioos owns repo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with: { ref: main }

    - name: submodule checkout
      run: |
           git submodule update --init
    - name: check submodule status
      run: |
          git submodule status
    - name: Update theme from submodules
      run: |
           git submodule update --remote --merge
    - name: check submodule status 2
      run: |
           git submodule status
    - name: Commit and push if it changed
      run: |
           git config user.name "Automated"
           git config user.email "actions@users.noreply.github.com"
           git add -A
           timestamp=$(date -u)
           git commit -m "Update theme on: ${timestamp}" || exit 0
           git push
